name: mp
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - keras=2.11.0
  - keras-preprocessing=1.1.2
  - pandas=1.4.2
  - python=3.8.16
  - sqlite=3.40.1
  - pip:
    - matplotlib==3.6.3
    - mediapipe==0.9.1.0
    - tensorflow==2.11.1
    - numpy==1.24.1
    - opencv-contrib-python==4.4.0.42
    - opencv-python==4.4.0.42
    - pyautogui==0.9.54
    - pynput==1.7.7